name: Deploy App

on:
  push: 
    branches:
      - main
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS OIDC authentication
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubOIDCSession
          aws-region: ap-south-1

      - name: Install Dependencies
        run: |
          cd app
          npm install

      - name: Zip Lambda Function
        run: |
          cd app
          zip -r ../lambda.zip .
          cd ..

      - name: Update Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name hello-world-${{ github.ref_name == 'main' && 'prod' || 'dev' }} \
            --zip-file fileb://lambda.zip \
            --region ap-south-1
