name: Deploy App

on: 
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS OIDC authentication
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Install Dependencies
        run: |
          cd app
          /* npm install */
          rm -rf node_modules && npm install

      - name: Zip Lambda Function
        run: |
          cd app
          zip -r ../lambda.zip .
          cd ..

      - name: Wait for Lambda to be Ready
        run: |
          FUNCTION_NAME="hello-world-${{ github.ref_name == 'main' && 'prod' || 'dev' }}"
          for i in {1..10}; do
            if aws lambda get-function --function-name $FUNCTION_NAME --region ap-south-1; then
              echo "Lambda function exists."
              exit 0
            fi
            echo "Waiting for Lambda to be created..."
            sleep 10
          done
          echo "ERROR: Lambda function $FUNCTION_NAME not found!"
          exit 1

      - name: Update Lambda Function
        run: |
          FUNCTION_NAME="hello-world-${{ github.ref_name == 'main' && 'prod' || 'dev' }}"
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --zip-file fileb://lambda.zip \
            --region ap-south-1

